# Generated by Django 3.2.13 on 2024-02-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_baskets_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_produc_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
